### ISSUE TITLE
MNN Graph tests fail randomly

### ISSUE THREAD

**Issue by scottgigante** [KrishnaswamyLab/graphtools#11]
Sometimes (not always, and infrequently enough for tests to pass) the MNN kernel tests fail as follows:

```
======================================================================
FAIL: test_mnn.transplant_class.<locals>.C (test_mnn_graph_float_gamma)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/old/home/scottgigante/sync/1_soft/graphtools/test/test_mnn.py", line 151, in test_mnn_graph_float_gamma
    assert np.all(G.d == G2.d)
AssertionError

======================================================================
FAIL: test_mnn.transplant_class.<locals>.C (test_mnn_graph_matrix_gamma)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/old/home/scottgigante/sync/1_soft/graphtools/test/test_mnn.py", line 206, in test_mnn_graph_matrix_gamma
    assert np.all(G.d == G2.d)
AssertionError

----------------------------------------------------------------------
```

Running the same command again nearly always fixes the problem.

**Comment by scottgigante** [comment]
Resolved by 718d191989f19a0f9cde1350e2920e370048cde6
